export const users = [
    {
      "_id": "663ccb02daa739b458e0a83a",
      "index": 0,
      "guid": "58072475-3277-425d-90e5-2cdc7adc8058",
      "isActive": true,
      "balance": "$3,175.57",
      "picture": "http://placehold.it/32x32",
      "age": 37,
      "eyeColor": "brown",
      "name": "Moreno Russo",
      "gender": "male",
      "company": "PYRAMIS",
      "email": "morenorusso@pyramis.com",
      "phone": "+1 (843) 409-2527",
      "address": "457 Colonial Road, Lewis, Texas, 5692",
      "about": "Veniam voluptate non eiusmod sit ipsum consequat voluptate cillum deserunt incididunt mollit et. Mollit culpa consectetur amet laboris aute. Do duis qui occaecat incididunt in duis commodo. In esse irure qui nulla culpa aliquip culpa ullamco sint tempor qui labore exercitation ullamco. Enim do culpa culpa ex ipsum irure.\r\n"
    },
    {
      "_id": "663ccb028a3049b972830f70",
      "index": 1,
      "guid": "0bd72be6-4f81-42a1-a676-e43657b2d2b8",
      "isActive": true,
      "balance": "$3,221.32",
      "picture": "http://placehold.it/32x32",
      "age": 37,
      "eyeColor": "brown",
      "name": "Jeannie Yang",
      "gender": "female",
      "company": "VICON",
      "email": "jeannieyang@vicon.com",
      "phone": "+1 (866) 524-2860",
      "address": "826 Post Court, Foscoe, South Carolina, 7060",
      "about": "Minim cillum voluptate elit aliqua sint ad eu laborum enim. Aliquip mollit commodo reprehenderit nulla adipisicing aliquip velit veniam do. Culpa minim adipisicing ea laborum tempor.\r\n"
    },
    {
      "_id": "663ccb02dc24b6d44d455c45",
      "index": 2,
      "guid": "5bc4cc67-93d2-4395-ba4d-611cdb226882",
      "isActive": false,
      "balance": "$1,411.71",
      "picture": "http://placehold.it/32x32",
      "age": 35,
      "eyeColor": "blue",
      "name": "Chapman Cunningham",
      "gender": "male",
      "company": "SAVVY",
      "email": "chapmancunningham@savvy.com",
      "phone": "+1 (880) 545-2881",
      "address": "750 Cooper Street, Magnolia, Virginia, 7564",
      "about": "Deserunt incididunt sint proident reprehenderit consequat voluptate eiusmod nostrud veniam exercitation reprehenderit aliqua. Aute laborum dolore nostrud do eu sint laboris sunt non duis pariatur. Proident est ullamco irure non exercitation in cillum velit occaecat id qui. Nulla velit enim reprehenderit qui cillum aliquip. Minim aliquip cillum ex aliqua.\r\n"
    },
    {
      "_id": "663ccb02acceee29d0341818",
      "index": 3,
      "guid": "5a3f5040-28c2-4421-a8ec-ba412d90cff8",
      "isActive": false,
      "balance": "$2,434.92",
      "picture": "http://placehold.it/32x32",
      "age": 23,
      "eyeColor": "blue",
      "name": "Rena Landry",
      "gender": "female",
      "company": "FANGOLD",
      "email": "renalandry@fangold.com",
      "phone": "+1 (918) 402-2382",
      "address": "346 Chester Court, Zarephath, Nevada, 6043",
      "about": "Et consequat culpa dolore voluptate. Esse exercitation sunt sunt sint veniam magna occaecat exercitation exercitation sint est. Quis reprehenderit fugiat id aliqua aute consectetur tempor. Velit dolore sint ex laboris magna nostrud anim occaecat proident excepteur fugiat. Ut consequat tempor duis sunt eu exercitation do Lorem aliqua dolore.\r\n"
    },
    {
      "_id": "663ccb0298cc615a02ad6cf3",
      "index": 4,
      "guid": "926dba75-eb89-4075-aa88-1891c0dba1b9",
      "isActive": false,
      "balance": "$3,787.56",
      "picture": "http://placehold.it/32x32",
      "age": 30,
      "eyeColor": "brown",
      "name": "Justice Booker",
      "gender": "male",
      "company": "COMDOM",
      "email": "justicebooker@comdom.com",
      "phone": "+1 (953) 470-3490",
      "address": "684 Brighton Avenue, Nelson, Minnesota, 6122",
      "about": "Commodo eiusmod eiusmod duis reprehenderit tempor. Do aute eu cillum cupidatat nostrud deserunt dolor elit elit labore id elit pariatur. Voluptate mollit est et tempor. Cillum ut veniam pariatur aliquip. Velit deserunt culpa id quis non Lorem sunt eu commodo irure nisi irure. Sunt ut veniam esse ad sunt. Nisi elit quis deserunt magna.\r\n"
    },
    {
      "_id": "663ccb020bbad74bac7e4331",
      "index": 5,
      "guid": "02103e6a-fafe-435c-b4b4-360d63970ce0",
      "isActive": true,
      "balance": "$2,027.35",
      "picture": "http://placehold.it/32x32",
      "age": 24,
      "eyeColor": "blue",
      "name": "Barron Carlson",
      "gender": "male",
      "company": "GENEKOM",
      "email": "barroncarlson@genekom.com",
      "phone": "+1 (986) 407-2517",
      "address": "256 Matthews Court, Reinerton, Florida, 7726",
      "about": "Qui ut ad labore aliqua veniam. Elit tempor et adipisicing culpa qui id esse nulla et tempor aute pariatur cillum. Adipisicing esse exercitation sunt proident exercitation irure Lorem sit. Cupidatat cillum laborum nulla aliquip irure. Do veniam consequat est et esse do tempor.\r\n"
    },
    {
      "_id": "663ccb02830c9c36ab55dff1",
      "index": 6,
      "guid": "b2d3d56b-fe8b-4a07-84c0-e7eee58b0384",
      "isActive": false,
      "balance": "$1,697.46",
      "picture": "http://placehold.it/32x32",
      "age": 30,
      "eyeColor": "green",
      "name": "Roseann Andrews",
      "gender": "female",
      "company": "RAMJOB",
      "email": "roseannandrews@ramjob.com",
      "phone": "+1 (805) 407-2737",
      "address": "609 McClancy Place, Brookfield, Guam, 808",
      "about": "Duis ullamco ex pariatur Lorem proident laborum amet. Aliquip non labore elit culpa ipsum dolor dolor eu commodo. Quis amet sit in consectetur aliquip.\r\n"
    }
  ]